# Use postgres/example user/password credentials
services:
  nginx:
    build:      
      dockerfile: webserver/Dockerfile
    container_name: nginx
    ports:      
      - "443:443"
    depends_on:
      - postgres
    volumes:
      - webserver_data:/usr/share/nginx/html    
    restart: always
  
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data    
#    environment:
#     POSTGRES_USER: ${POSTGRES_USER}
#     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#     POSTGRES_DB: ${POSTGRES_DB}      

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

networks:
  pong-network:
    driver: bridge

volumes:
  postgres_data:
  webserver_data:

#volumes:
#  database:
#    driver: local
#    driver_opts:
#      type: 'none' 
#      o: 'bind'
#      device: '/home/${LOGIN}/data/postgres' 

#     user_service:
#        driver: local # specify the driver for the volume 
#        driver_opts:
#          type: 'none'
#          o: 'bind'
#          device: '.'  # Ou stocker le dossier sur votre ordinateur en local
