# Use postgres/example user/password credentials
services:
  nginx:
    build:      
      dockerfile: webserver/Dockerfile
    container_name: nginx
    ports:      
      - "443:443"
    depends_on:
      - postgres
    volumes:
      - webserver_data:/usr/share/nginx/html    
    restart: always
    networks:
      - pong-network
    
  
  back-end:
    build:      
      dockerfile: back-end/Dockerfile
    container_name: back-end
    expose:      
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - back-end_data:/usr/src/app  
    restart: always
    networks:
      - pong-network


  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pong-network  


networks:
  pong-network:
    driver: bridge

volumes:
  postgres_data:
  webserver_data:
  back-end_data:

#volumes:
#  database:
#    driver: local
#    driver_opts:
#      type: 'none' 
#      o: 'bind'
#      device: '/home/${LOGIN}/data/postgres' 

#     user_service:
#        driver: local # specify the driver for the volume 
#        driver_opts:
#          type: 'none'
#          o: 'bind'
#          device: '.'  # Ou stocker le dossier sur votre ordinateur en local
