global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'back-end'
    static_configs:
      - targets: ['back-end:8000']
    metrics_path: api/metrics

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres:5432']
