<template>
  <div class="modal-overlay">
    <Card class="modal-card">
      <h2 class="modal-title">{{ $t('game-withfriend') }}</h2>
      <p class="modal-text">{{ $t('join-create-match') }}</p>

      <div class="button-group">
        <Button class="btn" variant="secondary" @click="handleCreate">
          {{ $t('create-game') }}
        </Button>
      </div>

      <!-- Only show the generated code if in create mode and a code exists -->
      <div v-if="isCreatingPrivateRoom && privateRoomCode" class="created-match-code">
        <p>{{ $t('match-id') }}</p>
        <div class="code-display">
          <input
            :value="privateRoomCode"
            type="text"
            readonly
            class="generated-code-input"
          />
          <button class="copy-btn" :class="{ copied: isCopied }" @click="copyToClipboard">
            {{ $t('copy') }}
          </button>
        </div>
      </div>

      <!-- Input for joining a room -->
      <div class="form-group">
        <input
          v-model="joinCode"
          type="text"
          placeholder="Enter match code"
          class="match-code-input"
        />
        <Button class="btn" variant="primary" @click="joinPrivateRoom">
          {{ $t('join-game') }}
        </Button>
      </div>
    </Card>
  </div>
</template>

<script>
import Card from "@/components/atoms/Card.vue";
import Button from "@/components/atoms/Button.vue";

export default {
  name: "PrivateMatch",
  components: { Card, Button },
  data() {
    return {
      isCreatingPrivateRoom: false,
      isJoiningPrivateRoom: false,
      privateRoomCode: "", // Room code generated by the server
      joinCode: "", // Code entered by a user joining a match
      currentGameMode: null,
      gameSocket: null,
      isCopied: false,
    };
  },
  methods: {
    // Called when "create game" is clicked
    handleCreate() {
      this.showCreatePrivateRoom();
      this.createPrivateRoom();
    },
    // Set the UI state for creating a room
    showCreatePrivateRoom() {
      this.isCreatingPrivateRoom = true;
      this.isJoiningPrivateRoom = false;
      this.privateRoomCode = "";
      this.joinCode = "";
    },
    // Create a private room by generating a code and connecting in "create_private" mode
    createPrivateRoom() {
      this.privateRoomCode = "Generating..."; // temporary message
      this.startGameMode("create_private");
    },
    // Join a private room by opening a connection in "join_private" mode
    joinPrivateRoom(event) {
      if (event && event.preventDefault) event.preventDefault();
      if (this.joinCode && this.joinCode.trim() !== "") {
        console.log("Joining private room with code:", this.joinCode);
        this.showJoinPrivateRoom();
        this.startGameMode("join_private");
      } else {
        alert("Veuillez entrer un code de room privée.");
      }
    },
    // Set UI state for joining a room
    showJoinPrivateRoom() {
      this.isJoiningPrivateRoom = true;
      this.isCreatingPrivateRoom = false;
      // For join, we typically don't display a generated code
      this.privateRoomCode = "";
    },
    // Save the game mode and connect via WebSocket
    startGameMode(mode) {
      this.currentGameMode = mode;
      this.connectToGame(mode);
    },
    // Connect to the game server via WebSocket and send the appropriate init message
    connectToGame(gameMode) {
      if (this.gameSocket) return;
      const roomName = "default_room"; // Adjust for dynamic room naming if needed
      this.gameSocket = new WebSocket(`wss://${window.location.host}/ws/friendPong/${roomName}/`);
      
      this.gameSocket.onopen = () => {
        let initMessagePayload = {
          type: "init",
          info: {
            game: gameMode,
          },
        };
        if (gameMode === "join_private") {
          initMessagePayload.info.join_code = this.joinCode;
        }
        this.gameSocket.send(JSON.stringify(initMessagePayload));
      };
      
      this.gameSocket.onmessage = (event) => {
        const data = JSON.parse(event.data);
        const messageType = data.type;
        
        if (messageType === "players_ready") {
          // When both players are connected, emit an event for the parent to start the match
          this.$emit("match-ready", { code: this.privateRoomCode, mode: this.currentGameMode });
        } else if (messageType === "private_room_code") {
          // Update the room code once generated by the backend
          this.privateRoomCode = data.code;
        }
        // You can handle other message types as needed...
      };
      
      this.gameSocket.onclose = () => {
        this.gameSocket = null;
      };
    },
    // Utility: Copy the generated room code to the clipboard
    copyToClipboard() {
      const el = document.createElement("textarea");
      el.value = this.privateRoomCode;
      document.body.appendChild(el);
      el.select();
      document.execCommand("copy");
      document.body.removeChild(el);
      
      this.isCopied = true;
      setTimeout(() => {
        this.isCopied = false;
      }, 1000);
    },
  },
};
</script>

<style scoped>
/* (Your existing styles remain unchanged) */
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background: rgba(0, 0, 0, 0.397);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 10000;
}
.modal-card {
  width: 90%;
  max-width: 400px;
  padding: 20px;
  border-radius: 10px;
  color: #fff;
  text-align: center;
}
.modal-title {
  font-size: 1.8rem;
  margin-bottom: 10px;
}
.modal-text {
  font-size: 1rem;
  margin-bottom: 20px;
}
.button-group {
  display: flex;
  justify-content: space-around;
  margin-bottom: 20px;
}
.form-group {
  margin-bottom: 20px;
}
.match-code-input {
  width: 100%;
  padding: 10px;
  font-size: 1rem;
  border: 1px solid #ccc;
  border-radius: 5px;
  box-sizing: border-box;
  margin: 15px 0 13px;
}
.btn {
  padding: 10px;
  margin-top: 15px;
}
.created-match-code {
  margin: 15px 0;
  padding: 10px;
  background-color: var(--background-light);
  border-radius: 8px;
}
.code-display {
  display: flex;
  gap: 10px;
  margin-top: 10px;
}
.generated-code-input {
  flex: 1;
  padding: 8px;
  border: 1px solid #cccccc94;
  border-radius: 4px;
  background-color: var(--card-color);
  color: white;
}
.copy-btn {
  padding: 8px 15px;
  background-color: #4CAF50;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}
.copy-btn:hover {
  background-color: #45a049;
}
.copy-btn.copied {
  animation: copied-animation 0.5s ease-in-out;
}
@keyframes copied-animation {
  0% { background-color: #4CAF50; }
  50% { background-color: #45a049; transform: scale(0.95); }
  100% { background-color: #4CAF50; }
}
@media (max-width: 768px) {
  .modal-card {
    height: 65%;
    width: 78%;
  }
}
</style>
