# Generated by Django 5.1.5 on 2025-02-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestats', '0002_pongsolo_delete_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pongsolo',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pongsolo',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pongsolo',
            name='rank_player1_begin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pongsolo',
            name='rank_player1_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pongsolo',
            name='rank_player2_begin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pongsolo',
            name='rank_player2_change',
            field=models.IntegerField(default=0),
        ),
    ]
