# Generated by Django 5.1.5 on 2025-02-09 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestats', '0003_alter_pongsolo_player1_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pongsolo',
            name='type',
            field=models.CharField(default='solo', max_length=50),
        ),
        migrations.AlterField(
            model_name='pongsolo',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sololoser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pongsolo',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soloplayer1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pongsolo',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soloplayer2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pongsolo',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solowinner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PongMulti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('player3_score', models.IntegerField(default=0)),
                ('player4_score', models.IntegerField(default=0)),
                ('rank_player1_begin', models.IntegerField(default=0)),
                ('rank_player2_begin', models.IntegerField(default=0)),
                ('rank_player3_begin', models.IntegerField(default=0)),
                ('rank_player4_begin', models.IntegerField(default=0)),
                ('rank_player1_change', models.IntegerField(default=0)),
                ('rank_player2_change', models.IntegerField(default=0)),
                ('rank_player3_change', models.IntegerField(default=0)),
                ('rank_player4_change', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default='solo', max_length=50)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiplayer1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiplayer2', to=settings.AUTH_USER_MODEL)),
                ('player3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiplayer3', to=settings.AUTH_USER_MODEL)),
                ('player4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiplayer4', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multiwinner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PongTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final', to='gamestats.pongsolo')),
                ('semi_final_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semi_final_1', to='gamestats.pongsolo')),
                ('semi_final_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semi_final_2', to='gamestats.pongsolo')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_turn', models.IntegerField(default=0)),
                ('player2_turn', models.IntegerField(default=0)),
                ('rank_player1_begin', models.IntegerField(default=0)),
                ('rank_player2_begin', models.IntegerField(default=0)),
                ('rank_player1_change', models.IntegerField(default=0)),
                ('rank_player2_change', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tttloser', to=settings.AUTH_USER_MODEL)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tttplayer1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tttplayer2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tttwinner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
