# Generated by Django 5.1.5 on 2025-02-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestats', '0004_pongsolo_type_alter_pongsolo_loser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pongmulti',
            name='type',
            field=models.CharField(default='multi', max_length=50),
        ),
    ]
