POST https://localhost:1443/api/register/
Content-Type: application/json

{ "username": "adasm1", "password": "Pass1234!", "email": "adams@msail.com" }

###

POST https://localhost:1443/api/token/
Content-Type: application/json

{ "username": "adasm1", "password": "Pass1234!" }

###

GET https://localhost:1443/api/profile/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4NDk0OTA1LCJpYXQiOjE3Mzg0OTQ2MDUsImp0aSI6ImJjZDU1NzI5MTZiNjRlNTE5ZTI3OGUzMzllNTBhNDEwIiwidXNlcl9pZCI6NSwidXNlcm5hbWUiOiJhZGFzbTEiLCJlbWFpbCI6ImFkYW1zQG1zYWlsLmNvbSJ9.Fkln-NGypOcpgUv6ZSj6pXr00wcKYTUoK2-IW8QnI-Q

###

POST https://localhost:1443/api/logout/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4NDk1MjkyLCJpYXQiOjE3Mzg0OTQ5OTIsImp0aSI6ImY1Y2YyMTY0OTI5YjQ5YjNhZTFhM2E2N2NiYTQwMWI4IiwidXNlcl9pZCI6NSwidXNlcm5hbWUiOiJhZGFzbTEiLCJlbWFpbCI6ImFkYW1zQG1zYWlsLmNvbSJ9.ajLTiPysWyzKsq2wNvB9N8aOaK-TFOmcLZtPCKBHwFE

{ "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0MjgxNDk5MiwiaWF0IjoxNzM4NDk0OTkyLCJqdGkiOiI2MTNmMzA1OTc0Zjg0MTU0OTZjNDZlYmMwMTExMjYyNyIsInVzZXJfaWQiOjUsInVzZXJuYW1lIjoiYWRhc20xIiwiZW1haWwiOiJhZGFtc0Btc2FpbC5jb20ifQ.4BWag-hobUpLpGoBRUcTzj91Hdze8oJaF-wv2aDFn-4" }
