# Generated by Django 5.1.5 on 2025-02-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgm', '0002_remove_customuser_bio_customuser_friends_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
