# Generated by Django 5.1.5 on 2025-02-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgm', '0003_alter_customuser_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cover_photo_url',
            field=models.URLField(blank=True),
        ),
    ]
