# Generated by Django 5.1.5 on 2025-02-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgm', '0004_customuser_cover_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cover_photo_url',
        ),
    ]
