# Generated by Django 5.1.5 on 2025-02-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgm', '0006_remove_customuser_friends_remove_customuser_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lang',
            field=models.CharField(default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.CharField(default='dark', max_length=10),
        ),
    ]
