# Generated by Django 5.1.5 on 2025-02-08 12:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgm', '0007_customuser_lang_customuser_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='stat_pong_solo_loss',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='stat_pong_solo_tournament_tot_nb_matches',
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_pong_multi_loss_tot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_pong_multi_loss_tot_max10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_pong_multi_loss_tot_min10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_pong_multi_loss_tot_min5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_pong_multi_progress',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_pong_multi_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_pong_multi_wins_tot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_pong_multi_wins_tot_max10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_pong_multi_wins_tot_min10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_pong_multi_wins_tot_min5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_pong_solo_tournament_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_ttt_loss_av_movm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_ttt_loss_tot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_ttt_progress',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_ttt_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_ttt_wins_av_movm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_ttt_wins_tot',
            field=models.IntegerField(default=0),
        ),
    ]
