# Generated by Django 5.1.5 on 2025-02-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgm', '0008_remove_customuser_stat_pong_solo_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_42',
            field=models.BooleanField(default=False),
        ),
    ]
