# Generated by Django 5.1.5 on 2025-02-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgm', '0010_customuser_mfa_enabled_customuser_mfa_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mfasecret',
        ),
        migrations.AddField(
            model_name='customuser',
            name='enc_mfa_secret',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
