# Generated by Django 5.1.5 on 2025-02-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgm', '0011_remove_customuser_mfasecret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mfa_verified',
        ),
    ]
