# Generated by Django 5.1.5 on 2025-02-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgm', '0012_remove_customuser_mfa_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stat_pong_multi_rank',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stat_pong_solo_rank',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stat_ttt_rank',
            field=models.IntegerField(default=1000),
        ),
    ]
