# Generated by Django 5.1.5 on 2025-02-18 11:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgm', '0013_alter_customuser_stat_pong_multi_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stat_pong_multi_progress',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[1000], size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stat_pong_solo_progress',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[1000], size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stat_ttt_progress',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[1000], size=None),
        ),
    ]
