# Generated by Django 5.1.5 on 2025-02-18 11:16

import django.contrib.postgres.fields
import user_mgm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgm', '0014_alter_customuser_stat_pong_multi_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stat_pong_multi_progress',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=user_mgm.models.default_progress, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stat_pong_solo_progress',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=user_mgm.models.default_progress, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stat_ttt_progress',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=user_mgm.models.default_progress, size=None),
        ),
    ]
