# Generated by Django 5.1.5 on 2025-02-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgm', '0015_alter_customuser_stat_pong_multi_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stat_ttt_loss_tot_max10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_ttt_loss_tot_min10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_ttt_loss_tot_min5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_ttt_wins_tot_max10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_ttt_wins_tot_min10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stat_ttt_wins_tot_min5',
            field=models.IntegerField(default=0),
        ),
    ]
